document.writeln("<div class=\"ad_artleft\">");
document.writeln("<script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>");
document.writeln("<!-- bkjia-title-zuobian -->");
document.writeln("<ins class=\"adsbygoogle\"");
document.writeln("     style=\"display:inline-block;width:300px;height:250px\"");
document.writeln("     data-ad-client=\"ca-pub-2290945697182720\"");
document.writeln("     data-ad-slot=\"1765117294\"></ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("</script>");
document.writeln("<\/div>");
document.writeln("<div class=\"ad_artright\">");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    /*bkjia-artitle250*250 创建于 2015-03-11*/");
document.writeln("    var cpro_id = \"u1983349\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/c.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<\/div>");